version: '3'
services:
    redis:
        image: 'redis:3.2.7'
        networks:
            - flow_application
        ports:
            - "6380:6380"

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        networks:
            - flow_application
        ports:
            - "5432:5432"
        deploy:
            placement:
                constraints: [node.role == worker]

    webserver:
        image: wongwill86/air-tasks:chunkflow
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=y
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - AIRFLOW_HOME=/usr/local/airflow
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        volumes:
            - ./dags/:/usr/local/airflow/dags
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - flow_application
        ports:
            - "8080:8080"
        command: webserver
        deploy:
            placement:
                constraints: [node.role == manager]

    flower:
        image: wongwill86/air-tasks:chunkflow
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        networks:
            - flow_application
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: wongwill86/air-tasks:chunkflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags/:/usr/local/airflow/dags
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - LOAD_EX=y
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - AIRFLOW_HOME=/usr/local/airflow
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        command: scheduler
        networks:
            - flow_application

    worker:
        image: wongwill86/air-tasks:chunkflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags/:/usr/local/airflow/dags
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - AIRFLOW_HOME=/usr/local/airflow
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        command: worker
        networks:
            - flow_application
    
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "81:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - flow_application

networks:
    flow_application:
        driver: overlay
        driver_opts:
            subnet: 10.0.9.0/24
            #encrypted: "true"
